name: scopa
description: "Scopa card game."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0
  flutter_webrtc: ^0.11.6+hotfix.1
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
